name: YouTube Downloader

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'لینک ویدیو یوتیوب'
        required: true

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install yt-dlp
        run: sudo apt-get update && sudo apt-get install -y yt-dlp
      - name: Download video
        run: yt-dlp -o "video.mp4" "${{ github.event.inputs.url }}"
      - name: Upload video
        uses: actions/upload-artifact@v4
        with:
          name: video
          path: video.mp4
